using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Threading.Tasks;

namespace D_OS_Save_Editor
{
    public class DataTable
    {
        public enum Attributes
        {
            Strength = 0,
            Dexerity,
            Intelligence,
            Consitution,
            Speed,
            Perception
        }

        public enum Abilities
        {
            ManAtArms = 0,
            ExpertMarksman,
            Scoundrel,
            SingleHanded,
            TwoHanded,
            PlaceHolder_1,
            Bow,
            Crossbow,
            ShieldSpecialist,
            PlaceHolder_2,
            ArmorSpecialist,
            Witchcraft,
            Telekinesis,
            Willpower,
            Pyrokinetic,
            Hydrosophist,
            Aerotheurge,
            Geomancer,
            Blacksmithing,
            Sneaking,
            Pickpocketing,
            Lockpicking,
            Loremaster,
            Crafting,
            Bartering,
            PlaceHolder_3,
            PlaceHolder_4,
            PlaceHolder_5,
            Charisma,
            Leadership,
            LuckyCharm,
            Bodybuilding,
            DuelWelding,
            Wand
        }

        public static string[] TalentNamesEffects =
        {
            "Spook",
            "Spook improves your telekinetic abilities.",
            "Tinkerer",
            "Tinkerer improves your ability to brew potions, prepare food, write scrolls...",
            "Sidewinder",
            "Sidewinder removes your defence penalty when flanked.",
            "Opportunist",
            "Opportunist gives you the ability to perform attacks of opportunity.",
            "Assassin",
            "Assassin allows you to backstab enemies with weapons other than a knife.",
            "Trader's Tongue",
            "Trader's Tongue improves your bartering techniques.",
            "Cat Burglar",
            "Cat Burglar improves your aptitude at picking locks.",
            "Marksman",
            "Marksman improves your chances to hit an opponent with ranged weapons in battle.",
            "Gladiator",
            "Gladiator improves your chances of hitting an opponent with melee weapons in battle.",
            "Warlord",
            "Warlord increases overall damage by 10%.",
            "Fleetfooted",
            "Fleetfooted increases your Maximum Action Points by 1.",
            "Rosy-Cheeked",
            "Rosy-Cheeked increases your maximum Action Points by 1.",
            "Killer Instinct",
            "Killer Instinct improves your chance to land critical hits by 5%.",
            "Indestructible",
            "Indestructible improves your armour rating.",
            "Hyperopia",
            "Hyperopia makes you farsighted, causing your ranged attacks to be precise at long distances, but inaccurate when your target is close by.",
            "Braveheart",
            "Braveheart increases your ability to resist fear by 25%.",
            "Stand Your Ground 2",
            "Stand Your Ground increases your ability to resist knockdown attacks by 25%.",
            "Lightning Rod 2",
            "Lightning Rod increases your ability to resist stun attacks by 25%.",
            "Mithridates",
            "Mithridates increases your ability to resist poison by 25%.",
            "Silver-tongued",
            "Silver-tongued increases your ability to resist being silenced by 25%. (When silenced you can no longer cast spells until the effect wears off.)",
            "Comeback Kid",
            "When an opponent lands the blow that should kill you, Comeback Kid will leave you with 1 health as long as you had more than 1 left.",
            "Packmule",
            "Packmule doubles the amount of weight you can carry.",
            "Catapult",
            "Catapult increases the max weight of objects you can throw and increases how far you can toss them.",
            "Grease Monkey",
            "Grease Monkey improves your ability to repair damaged items.",
            "Quick-Witted",
            "Quick-Witted increases the rate at which you gain experience by 10%.",
            "Bigger and Better",
            "Bigger and Better gives you 1 extra Attribute Point(s) to spend.",
            "All Skilled Up",
            "All Skilled Up gives you 2 extra Ability Points to spend.",
            "My Precious",
            "With My Precious, every time you hit or get hit, your gear has a 50% chance of not losing durability.",
            "Sixth Sense",
            "Sixth Sense increases your ability to hear and spot (hidden) things in and out of combat.",
            "Picture of Health 2",
            "Picture of Health 2 increases your total hitpoints by 20%.",
            "Pyromaniac",
            "Pyromaniac improves your casting ability for fire-based spells.",
            "Rainman",
            "Rainman improves your casting ability for water-based spells.",
            "Tempest",
            "Tempest improves your casting ability for air-based spells.",
            "Geomancer",
            "Geomancer improves your casting ability for earth-based spells.",
            "Prince Charming",
            "Prince Charming improves your ability to Charm people during dialogs.",
            "Intimidator",
            "Intimidator improves your ability to Intimidate people during dialogues.",
            "Rhetorician",
            "Rhetorician improves your ability to Reason with people during dialogues.",
            "Fortune's Favourite",
            "Fortune's Favourite increases your overall luck.",
            "Leader of the Pack",
            "Leader of the Pack increases your initiative by 5 at the onset of combat.",
            "Dress Rehearsal",
            "Dress Rehearsal decreases the number of Action Points it takes to equip different items during combat.",
            "Pussyfooter",
            "Pussyfooter makes you less prone to be detected while performing suspicious acts.",
            "Pet Pal",
            "Pet Pal enables you to talk to animals.",
            "Escapist",
            "Escapist allows you to flee combat even when enemies are right next to you.",
            "Stand Your Ground",
            "A character with Stand Your Ground cannot be knocked down.",
            "Guerrilla",
            "Guerrilla increases attack damage while sneaking by 50%.",
            "Light Stepper",
            "Light Stepper gives you a +2 Perception bonus for detecting traps and secrets.",
            "Morning Person",
            "When resurrected, you revive to full health.",
            "Scientist",
            "Scientist gives you a bonus point in Blacksmithing and one in Crafting.",
            "Glass Cannon",
            "Glass Cannon gives 4 extra Recovery Action Points, but your total Vitality is decreased by 50%.",
            "Know-it-All",
            "Know-it-All decreases everyone's attitude towards you by 20 but gives you 1 extra point in Intelligence.",
            "What a Rush",
            "What a Rush increases your Turn Action Points and Maximum Action Points by 2 when your vitality is below 30%.",
            "Far Out Man",
            "Far Out Man increases the range of spells and scrolls by 2m.",
            "Leech",
            "Leech heals you when standing in blood.",
            "Elemental Affinity",
            "Elemental Affinity lowers the Action Point cost of spells by 1 when standing in a surface of the same element.",
            "Five-Star Diner",
            "Five-Star Diner doubles the effects of food.",
            "Bully",
            "Bully boosts non-magical attacks by 50% against opponents with Slowed, Crippled or Knocked Down.",
            "Elemental Ranger",
            "Arrows will inflict bonus elemental damage depending on the surface your target is standing in.",
            "Lightning Rod",
            "Lightning Rod makes you immune to stun.",
            "Politician",
            "Politician gives you 2 bonus points in Charisma, but you lose a point in Intelligence.",
            "Weatherproof",
            "Weatherproof makes you immune to environmental effects.",
            "Lone Wolf",
            "A character with Lone Wolf can no longer have a companion but receives a 70% bonus to base vitality, 2 bonus to Turn Action Points and Maximum Action Points and an extra ability point on level up.",
            "Zombie",
            "Zombie lets you heal from poison but causes damage from regular healing.",
            "Demon",
            "A character with Demon has an extra 15% Fire Resistance, but takes a 15% penalty to Water Resistance. In addition the maximum Fire Resistance is raised by 10.",
            "Ice King",
            "A character with Ice King has an extra 15% Water Resistance, but takes a 15% penalty to Fire Resistance. In addition the maximum Water Resistance is raised by 10.",
            "Courageous",
            "Courageous grants you immunity to Fear, but you can no longer flee from combat.",
            "Voluble Mage",
            "Voluble Mage grants you immunity to Muted.",
            "Walk it Off",
            "Walk it Off reduces the duration of statuses that have a Bodybuilding saving throw by one turn.",
            "Speedcreeper",
            "A character with Speedcreeper moves at normal speed while sneaking.",
            "Anaconda",
            "Anaconda increases your damage with crushing weapons by 10%.",
            "Stench",
            "Stench decreases everyone's attitude toward you by 25, but melee opponents will find you less attractive in combat.",
            "Kickstarter",
            "A character with Kickstarter will find certain secrets throughout the game.",
            "Thick Skin",
            "Thick Skin gives you extra armour equal to your Man-At-Arms ability + 5.",
            "Picture of Health",
            "Picture of Health gives you 3% x Man-at-Arms extra Vitality.",
            "Iron Hide",
            "Iron Hide gives you 3% x Man-at-Arms extra Elemental Resistance.",
            "Arrow Recovery",
            "Arrow Recovery gives you 33% chance to recover a special arrow after shooting it.",
            "Sidestep",
            "Sidestep gives you 10% extra chance to evade hits.",
            "Quickdraw",
            "Quickdraw increases attack range of Bows and Crossbows by 1m.",
            "Mack the Knife",
            "Mack the Knife reduces 1AP from the cost of using daggers and knives.",
            "Back-Stabber",
            "Back-Stabber allows a character to backstab with daggers, knives, rondels and rapiers.",
            "Swift Footed",
            "Swift Footed gives you a 10% movement bonus.",
            "Headstrong",
            "Headstrong gives you 20% bonus against being Frozen, Stunned, Petrified and Knocked Down..",
            "Avoid Opportunists",
            "Avoid Opportunists gives you the ability to evade attacks of opportunity.",
            "Slingshot",
            "Slingshot adds a 5 meter distance to your grenade throws.",
            "Pinpoint",
            "With Pinpoint, your grenade throws will never miss again.",
            "Magician",
            "Gives your one extra use of a wand skill.",
            "Parry Master",
            "Parry Master grants 10% Blocking Chance while dual wielding."
        };

        public static bool[] TalentIsHidden =
        {
            true,
            true,
            false,
            false,
            true,
            true,
            true,
            true,
            true,
            true,
            true,
            true,
            true,
            true,
            false,
            true,
            true,
            true,
            true,
            true,
            false,
            false,
            true,
            true,
            true,
            false,
            false,
            false,
            true,
            true,
            true,
            true,
            true,
            true,
            true,
            true,
            true,
            true,
            true,
            true,
            true,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            true,
            false,
            false,
            false,
            false,
            false,
            true,
            true,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false
        };

        public static string[] Skills =
        {

        };

        /// <summary>
        /// Names used for Gold category items
        /// </summary>
        public static readonly string[] GoldNames =
            {"small_gold", "inbetween_gold", "trader_large_gold", "trader_insane_gold"};

        /// <summary>
        /// Names used for Arrow category items. Arrow items have prefix WPN which is shared with the Weapon category. Therefore, we need these strings to identify the Arrow category.
        /// </summary>
        public static readonly string[] ArrowTypeNames = {"arrow", "arrowhead", "arrowshaft"};

        public static string[] TraitNames =
        {
            "Forgiving",
            "Vindictive",
            "Bold",
            "Cautious",
            "Altruistic",
            "Egotistical",
            "Independent",
            "Obedient",
            "Pragmatic",
            "Romantic",
            "Spiritual",
            "Materialistic",
            "Righteous",
            "Renegade",
            "Blunt",
            "Considerate",
            "Compassionate",
            "Heartless"
        };

        public static string[] TraitEffects =
        {
            "Immune to Cursed",
            "+20% chance to hit on attacks of opportunity",
            "+1 Initiative",
            "+1 Sneaking",
            "+2 Reputation",
            "+1 Bartering",
            "+1 Willpower",
            "+1 Willpower when an ally with Leadership is in sight (+2 Willpower if ally has Leadership 5 or higher)",
            "+1 Crafting",
            "+1 Lucky Charm",
            "Immune to Fear",
            "+1 Loremaster",
            "+1 Leadership",
            "+1 Pickpocketing",
            "Immune to Charmed",
            "+1 Charisma",
            "`+3% Critical Chance",
            "+20% chance to hit when backstabbing"
        };

        public static string[] GenerationBoostsFilterNames =
        {
            "armor",
            "weapon",
            "amulet",
            "belt",
            "body",
            "garment",
            "gloves",
            "shoes",
            "helmet",
            "ring",
            "shield",
            "axe",
            "bow",
            "club",
            "knife",
            "spear",
            "sword",
            "staff",
            "wand",
            "2h",
            "wpn",
            "arm"
        };

        public static string[] GenerationBoosts =
        {
            "Armor__Amulet_Boost_Barter_Mod",
            "Armor__Amulet_Boost_Blackrock_Mod",
            "Armor__Amulet_Boost_Charisma_Mod",
            "Armor__Amulet_Boost_DEX_Mod",
            "Armor__Amulet_Boost_DEX_Mod_Large",
            "Armor__Amulet_Boost_HearingBoost_Mod",
            "Armor__Amulet_Boost_Initiative_Mod",
            "Armor__Amulet_Boost_INT _Mod_Large",
            "Armor__Amulet_Boost_INT_Mod",
            "Armor__Amulet_Boost_INT_Mod_Large",
            "Armor__Amulet_Boost_Loremaster_Mod",
            "Armor__Amulet_Boost_MuteImmunity",
            "Armor__Amulet_Boost_PoisonRes_Mod",
            "Armor__Amulet_Boost_PoisonRes_Mod_Large",
            "Armor__Amulet_Boost_ShadowRes_Mod",
            "Armor__Amulet_Boost_ShadowRes_Mod_Large",
            "Armor__Amulet_Boost_SightBoost_Mod",
            "Armor__Amulet_Boost_SPD_Mod_Large",
            "Armor__Amulet_Boost_STR_Mod",
            "Armor__Amulet_Boost_STR_Mod_Large",
            "Armor__Amulet_Boost_Value_Mod",
            "Armor__Amulet_Boost_VitalityBoost_Mod",
            "Armor__Amulet_Boost_VitalityBoost_Mod_LargeEarly",
            "Armor__Amulet_Boost_VitalityBoost_Mod_LargeLate",
            "Armor__Amulet_Boost_VitalityBoost_Mod_Late",
            "Armor__Amulet_Boost_VitalityBoost_Mod_Mid",
            "Armor__AmuletBoost_Initiative_Mod_Late",
            "Armor__AmuletBoost_Initiative_Mod_Mid",
            "Armor__Armor_Boost_BleedingImmunityLeather",
            "Armor__Armor_Boost_BleedingImmunityLeather_Late",
            "Armor__Armor_Boost_BlindImmunity",
            "Armor__Armor_Boost_BurnContact_All",
            "Armor__Armor_Boost_BurnContactMail",
            "Armor__Armor_Boost_BurnContactPlate",
            "Armor__Armor_Boost_BurnImmunity_All",
            "Armor__Armor_Boost_BurnImmunityMail",
            "Armor__Armor_Boost_BurnImmunityPlate",
            "Armor__Armor_Boost_ChillContact",
            "Armor__Armor_Boost_CrippledImmunityBoots",
            "Armor__Armor_Boost_CrippledImmunityMail",
            "Armor__Armor_Boost_CrippledImmunityPlate",
            "Armor__Armor_Boost_CursedImmunityRobe",
            "Armor__Armor_Boost_CursedImmunityRobe_Late",
            "Armor__Armor_Boost_FearImmunityMail",
            "Armor__Armor_Boost_FearImmunityMail_Late",
            "Armor__Armor_Boost_FreezeContact_All",
            "Armor__Armor_Boost_FreezeContactMail",
            "Armor__Armor_Boost_FreezeContactPlate",
            "Armor__Armor_Boost_FreezeImmunityMail",
            "Armor__Armor_Boost_FreezeImmunityPlate",
            "Armor__Armor_Boost_KnockdownImmunity_All",
            "Armor__Armor_Boost_KnockdownImmunityMail",
            "Armor__Armor_Boost_KnockdownImmunityPlate",
            "Armor__Armor_Boost_MuteImmunity",
            "Armor__Armor_Boost_MuteImmunityRobe",
            "Armor__Armor_Boost_MuteImmunityRobe_Late",
            "Armor__Armor_Boost_PetrifiedImmunityMail",
            "Armor__Armor_Boost_PetrifiedImmunityPlate",
            "Armor__Armor_Boost_PoisonContact_All",
            "Armor__Armor_Boost_PoisonContactLeather",
            "Armor__Armor_Boost_PoisonImmunity_All",
            "Armor__Armor_Boost_PoisonImmunityLeather",
            "Armor__Armor_Boost_PoisonImmunityMail",
            "Armor__Armor_Boost_PoisonImmunityPlate",
            "Armor__Armor_Boost_SlowedImmunity",
            "Armor__Armor_Boost_StunContact_All",
            "Armor__Armor_Boost_StunContactMail",
            "Armor__Armor_Boost_StunContactPlate",
            "Armor__Armor_Boost_StunImmunityMail",
            "Armor__Armor_Boost_StunImmunityPlate",
            "Armor__Belt_Boost_BodyBuilding_Mod",
            "Armor__Belt_Boost_Bow_Mod",
            "Armor__Belt_Boost_Crafting_Mod",
            "Armor__Belt_Boost_Crossbow_Mod",
            "Armor__Belt_Boost_DEX_Mod",
            "Armor__Belt_Boost_Initiative_Mod",
            "Armor__Belt_Boost_Initiative_Mod_Late",
            "Armor__Belt_Boost_Initiative_Mod_Mid",
            "Armor__Belt_Boost_Lockpicking_Mod",
            "Armor__Belt_Boost_Repair_Mod",
            "Armor__Belt_Boost_Shield_Mod",
            "Armor__Belt_Boost_STR_Mod",
            "Armor__Belt_Boost_STR_Mod_Late",
            "Armor__Belt_Boost_TwoHanded_Mod",
            "Armor__Belt_Boost_XBow_Mod",
            "Armor__Body_Boost_AirRes_ModHuge",
            "Armor__Body_Boost_AirRes_ModLarge",
            "Armor__Body_Boost_AirRes_ModLargeMail",
            "Armor__Body_Boost_AirRes_ModLargePlate",
            "Armor__Body_Boost_AirRes_ModNormal",
            "Armor__Body_Boost_AirRes_ModNormal_Late",
            "Armor__Body_Boost_ArmorMastery_ModMail",
            "Armor__Body_Boost_ArmorMastery_ModPlate",
            "Armor__Body_Boost_CON_Mod",
            "Armor__Body_Boost_CON_Mod_Late",
            "Armor__Body_Boost_DEX_Mod",
            "Armor__Body_Boost_DEX_Mod_Late",
            "Armor__Body_Boost_EarthRes_ModHuge",
            "Armor__Body_Boost_EarthRes_ModLarge",
            "Armor__Body_Boost_EarthRes_ModLargeMail",
            "Armor__Body_Boost_EarthRes_ModLargePlate",
            "Armor__Body_Boost_EarthRes_ModNormal",
            "Armor__Body_Boost_EarthRes_ModNormal_Late",
            "Armor__Body_Boost_FireRes_ModHuge",
            "Armor__Body_Boost_FireRes_ModLarge",
            "Armor__Body_Boost_FireRes_ModLargeMail",
            "Armor__Body_Boost_FireRes_ModLargePlate",
            "Armor__Body_Boost_FireRes_ModNormal",
            "Armor__Body_Boost_FireRes_ModNormal_Late",
            "Armor__Body_Boost_INT_Mod",
            "Armor__Body_Boost_INT_Mod_Late",
            "Armor__Body_Boost_INT_ModRobe",
            "Armor__Body_Boost_Movement_ClothMod",
            "Armor__Body_Boost_Movement_ClothMod_Early",
            "Armor__Body_Boost_Movement_ClothMod_LargeMid",
            "Armor__Body_Boost_Movement_ClothMod_Late",
            "Armor__Body_Boost_Movement_ClothMod_Mid",
            "Armor__Body_Boost_Movement_Mod",
            "Armor__Body_Boost_Movement_Mod_Late",
            "Armor__Body_Boost_Movement_Mod_Mid",
            "Armor__Body_Boost_PER_Mod",
            "Armor__Body_Boost_PER_Mod_Late",
            "Armor__Body_Boost_Ranged",
            "Armor__Body_Boost_SPD_Mod",
            "Armor__Body_Boost_SPD_Mod_Late",
            "Armor__Body_Boost_STR_Mod",
            "Armor__Body_Boost_STR_Mod_Late",
            "Armor__Body_Boost_Value_Mod",
            "Armor__Body_Boost_VitalityBoost_Mod",
            "Armor__Body_Boost_VitalityBoost_Mod_LargeEarly",
            "Armor__Body_Boost_VitalityBoost_Mod_LargeMid",
            "Armor__Body_Boost_VitalityBoost_Mod_Late",
            "Armor__Body_Boost_VitalityBoost_Mod_Mid",
            "Armor__Body_Boost_WaterRes_ModHuge",
            "Armor__Body_Boost_WaterRes_ModLarge",
            "Armor__Body_Boost_WaterRes_ModLargeMail",
            "Armor__Body_Boost_WaterRes_ModLargePlate",
            "Armor__Body_Boost_WaterRes_ModNormal",
            "Armor__Body_Boost_WaterRes_ModNormal_Late",
            "Armor__Garment_Boost_AirRes_Mod",
            "Armor__Garment_Boost_AirRes_ModCombo",
            "Armor__Garment_Boost_AirRes_ModLarge",
            "Armor__Garment_Boost_AirRes_ModLate",
            "Armor__Garment_Boost_AirRes_ModSmall",
            "Armor__Garment_Boost_BodyBuilding_Mod",
            "Armor__Garment_Boost_DEX_Mod",
            "Armor__Garment_Boost_DEX_ModLate",
            "Armor__Garment_Boost_EarthRes_Mod",
            "Armor__Garment_Boost_EarthRes_ModCombo",
            "Armor__Garment_Boost_EarthRes_ModLarge",
            "Armor__Garment_Boost_EarthRes_ModLate",
            "Armor__Garment_Boost_EarthRes_ModSmall",
            "Armor__Garment_Boost_FireRes_Mod",
            "Armor__Garment_Boost_FireRes_ModCombo",
            "Armor__Garment_Boost_FireRes_ModLarge",
            "Armor__Garment_Boost_FireRes_ModLate",
            "Armor__Garment_Boost_FireRes_ModSmall",
            "Armor__Garment_Boost_Initiative_Mod",
            "Armor__Garment_Boost_Initiative_Mod_Late",
            "Armor__Garment_Boost_Initiative_Mod_Mid",
            "Armor__Garment_Boost_INT_Mod",
            "Armor__Garment_Boost_INT_ModLate",
            "Armor__Garment_Boost_PoisonRes_Mod",
            "Armor__Garment_Boost_PoisonRes_ModLarge",
            "Armor__Garment_Boost_PoisonRes_ModLate",
            "Armor__Garment_Boost_PoisonRes_ModSmall",
            "Armor__Garment_Boost_ShadowRes_Mod",
            "Armor__Garment_Boost_ShadowRes_ModLarge",
            "Armor__Garment_Boost_STR_Mod",
            "Armor__Garment_Boost_STR_ModLate",
            "Armor__Garment_Boost_Value_Mod",
            "Armor__Garment_Boost_VitalityBoost_Mod",
            "Armor__Garment_Boost_VitalityBoost_Mod_LargeEarly",
            "Armor__Garment_Boost_VitalityBoost_Mod_LargeMid",
            "Armor__Garment_Boost_VitalityBoost_Mod_Late",
            "Armor__Garment_Boost_VitalityBoost_Mod_Mid",
            "Armor__Garment_Boost_WaterRes_Mod",
            "Armor__Garment_Boost_WaterRes_ModCombo",
            "Armor__Garment_Boost_WaterRes_ModLarge",
            "Armor__Garment_Boost_WaterRes_ModLate",
            "Armor__Garment_Boost_WaterRes_ModSmall",
            "Armor__Garment_Boost_Willpower_Mod",
            "Armor__Gloves_Boost_Crafting_Mod",
            "Armor__Gloves_Boost_DEX_Mod",
            "Armor__Gloves_Boost_Initiative_Mod",
            "Armor__Gloves_Boost_Initiative_Mod_Late",
            "Armor__Gloves_Boost_Initiative_Mod_Mid",
            "Armor__Gloves_Boost_Lockpicking_Mod",
            "Armor__Gloves_Boost_Pickpocket_Mod",
            "Armor__Gloves_Boost_Ranged_Mod",
            "Armor__Gloves_Boost_Ranged_Xbow_Mod",
            "Armor__Gloves_Boost_Repair_Mod",
            "Armor__Gloves_Boost_SingleHanded_Mod",
            "Armor__Gloves_Boost_Telekinesis_Mod",
            "Armor__Gloves_Boost_Value_Mod",
            "Armor__Helmet_Boost_ArmorMastery_Mod",
            "Armor__Helmet_Boost_ArmorMastery_Mod_Late",
            "Armor__Helmet_Boost_CON_Mod",
            "Armor__Helmet_Boost_CON_Mod_Late",
            "Armor__Helmet_Boost_HearingBoost_Mod",
            "Armor__Helmet_Boost_Leadership_Mod",
            "Armor__Helmet_Boost_PER_Mod",
            "Armor__Helmet_Boost_SightBoost_Mod",
            "Armor__Helmet_Boost_Sneaking_Mod",
            "Armor__Helmet_Boost_Value_Mod",
            "Armor__Helmet_Boost_VitalityBoost_Mod",
            "Armor__Helmet_Boost_VitalityBoost_Mod_LargeEarly",
            "Armor__Helmet_Boost_VitalityBoost_Mod_LargeLate",
            "Armor__Helmet_Boost_VitalityBoost_Mod_Late",
            "Armor__Helmet_Boost_VitalityBoost_Mod_Mid",
            "Armor__HelmetBoost_Initiative_Mod",
            "Armor__HelmetBoost_Initiative_Mod_Late",
            "Armor__HelmetBoost_Initiative_Mod_Mid",
            "Armor__Ring_Boost_Blackrock_Mod",
            "Armor__Ring_Boost_CON_Mod",
            "Armor__Ring_Boost_HearingBoost_Mod",
            "Armor__Ring_Boost_Lockpicking_Mod",
            "Armor__Ring_Boost_Loremaster_Mod",
            "Armor__Ring_Boost_Movement_Mod",
            "Armor__Ring_Boost_Movement_Mod_Large",
            "Armor__Ring_Boost_Movement_Mod_Medium",
            "Armor__Ring_Boost_Movement_Mod_Super",
            "Armor__Ring_Boost_PER_Mod",
            "Armor__Ring_Boost_Pickpocketing_Mod",
            "Armor__Ring_Boost_PoisonRes_Mod",
            "Armor__Ring_Boost_PoisonRes_Mod_Large",
            "Armor__Ring_Boost_ShadowRes_Mod",
            "Armor__Ring_Boost_ShadowRes_Mod_Large",
            "Armor__Ring_Boost_SightBoost_Mod",
            "Armor__Ring_Boost_SPD_Mod",
            "Armor__Ring_Boost_Telekinesis_Mod",
            "Armor__Ring_Boost_Value_Mod",
            "Armor__Shoes_Boost_ActionPoints_Mod",
            "Armor__Shoes_Boost_Air_Mod",
            "Armor__Shoes_Boost_Air_Mod_Large",
            "Armor__Shoes_Boost_Air_Mod_Mid",
            "Armor__Shoes_Boost_Air_Mod_Mid_Large",
            "Armor__Shoes_Boost_Air_ModLarge",
            "Armor__Shoes_Boost_Barter_Mod",
            "Armor__Shoes_Boost_Earth_Mod",
            "Armor__Shoes_Boost_Earth_Mod_Large",
            "Armor__Shoes_Boost_Earth_Mod_Mid",
            "Armor__Shoes_Boost_Earth_Mod_Mid_Large",
            "Armor__Shoes_Boost_Earth_ModLarge",
            "Armor__Shoes_Boost_Fire_Mod",
            "Armor__Shoes_Boost_Fire_Mod_Large",
            "Armor__Shoes_Boost_Fire_Mod_Mid",
            "Armor__Shoes_Boost_Fire_Mod_Mid_Large",
            "Armor__Shoes_Boost_Fire_ModLarge",
            "Armor__Shoes_Boost_Initiative_Mod",
            "Armor__Shoes_Boost_Initiative_Mod_Late",
            "Armor__Shoes_Boost_Initiative_Mod_Mid",
            "Armor__Shoes_Boost_Luck_Mod",
            "Armor__Shoes_Boost_Movement_Mod",
            "Armor__Shoes_Boost_Movement_Mod_Large",
            "Armor__Shoes_Boost_Movement_Mod_Medium",
            "Armor__Shoes_Boost_Movement_Mod_Super",
            "Armor__Shoes_Boost_Pickpocket_Mod",
            "Armor__Shoes_Boost_Sneaking_Mod",
            "Armor__Shoes_Boost_SnowBoots",
            "Armor__Shoes_Boost_SPD_Mod",
            "Armor__Shoes_Boost_Value_Mod",
            "Armor__Shoes_Boost_VitalityBoost_Mod",
            "Armor__Shoes_Boost_VitalityBoost_Mod_Huge",
            "Armor__Shoes_Boost_VitalityBoost_Mod_Large",
            "Armor__Shoes_Boost_VitalityBoost_Mod_Large_Late",
            "Armor__Shoes_Boost_Water_Mod",
            "Armor__Shoes_Boost_Water_Mod_Large",
            "Armor__Shoes_Boost_Water_Mod_Mid",
            "Armor__Shoes_Boost_Water_Mod_Mid_Large",
            "Armor__Shoes_Boost_Water_ModLarge",
            "Armor_Belt_Boost_Bow",
            "Armor_Belt_Boost_DualWield",
            "Armor_Belt_Boost_PoisonRes_Mod",
            "Armor_Belt_Boost_PoisonRes_ModLarge",
            "Armor_Belt_Boost_PoisonRes_ModLate",
            "Armor_Belt_Boost_PoisonRes_ModSmall",
            "Armor_Belt_Boost_ShadowRes_Mod",
            "Armor_Belt_Boost_ShadowRes_ModLarge",
            "Armor_Belt_Boost_VitalityBoost_Mod",
            "Armor_Belt_Boost_VitalityBoost_Mod_LargeEarly",
            "Armor_Belt_Boost_VitalityBoost_Mod_LargeLate",
            "Armor_Belt_Boost_VitalityBoost_Mod_Late",
            "Armor_Belt_Boost_VitalityBoost_Mod_Mid",
            "Armor_Body_Boost_BodyBuilding",
            "Armor_Body_Boost_Ranged",
            "Armor_Body_Boost_Ranged_Mod",
            "Armor_Body_Boost_Wands",
            "Armor_Body_Boost_Wands_Robe",
            "Armor_Boost_Amulet_Reflection_Air_Large",
            "Armor_Boost_Amulet_Reflection_Air_Legendary",
            "Armor_Boost_Amulet_Reflection_Air_Normal",
            "Armor_Boost_Amulet_Reflection_Earth_Large",
            "Armor_Boost_Amulet_Reflection_Earth_Legendary",
            "Armor_Boost_Amulet_Reflection_Earth_Normal",
            "Armor_Boost_Amulet_Reflection_Fire_Large",
            "Armor_Boost_Amulet_Reflection_Fire_Legendary",
            "Armor_Boost_Amulet_Reflection_Fire_Normal",
            "Armor_Boost_Amulet_Reflection_Water_Large",
            "Armor_Boost_Amulet_Reflection_Water_Legendary",
            "Armor_Boost_Amulet_Reflection_Water_Normal",
            "Armor_Boost_BurnContact_Ring",
            "Armor_Boost_DEX_Mod_Ring",
            "Armor_Boost_Dye_TOOL_Dye_Black",
            "Armor_Boost_Dye_TOOL_Dye_Blue",
            "Armor_Boost_Dye_TOOL_Dye_Candy",
            "Armor_Boost_Dye_TOOL_Dye_Gold",
            "Armor_Boost_Dye_TOOL_Dye_Green",
            "Armor_Boost_Dye_TOOL_Dye_Petrol",
            "Armor_Boost_Dye_TOOL_Dye_Purple",
            "Armor_Boost_Dye_TOOL_Dye_Red",
            "Armor_Boost_Dye_TOOL_Dye_Triad",
            "Armor_Boost_Dye_TOOL_Dye_White",
            "Armor_Boost_Dye_TOOL_Dye_Yellow",
            "Armor_Boost_FreezeContact_Ring",
            "Armor_Boost_Heal_CureWoundsKnight",
            "Armor_Boost_INT_Mod_Ring",
            "Armor_Boost_PoisonContact_Ring",
            "Armor_Boost_Projectile_BlitzBoltStartRing",
            "Armor_Boost_Projectile_BlitzBoltStartRingLate",
            "Armor_Boost_Projectile_FlareStartRing",
            "Armor_Boost_Projectile_FlareStartRingLate",
            "Armor_Boost_STR_Mod_Ring",
            "Armor_Boost_StunContact_Ring",
            "Armor_Boost_Target_Fortify",
            "Armor_Boost_Target_VampiricTouchRing",
            "Armor_Boost_Target_VampiricTouchRingLate",
            "Armor_Cone_WinterbreathMedium_Garment",
            "Armor_Gloves_Boost_VitalityBoost_Mod",
            "Armor_Gloves_Boost_VitalityBoost_Mod_LargeEarly",
            "Armor_Gloves_Boost_VitalityBoost_Mod_LargeLate",
            "Armor_Gloves_Boost_VitalityBoost_Mod_LargeLate ",
            "Armor_Gloves_Boost_VitalityBoost_Mod_Late",
            "Armor_Gloves_Boost_VitalityBoost_Mod_Mid",
            "Armor_Gloves_DefenseValue_ArmorBoost_Large",
            "Armor_Gloves_DefenseValue_ArmorBoost_Large_Late",
            "Armor_Gloves_DefenseValue_ArmorBoost_Large_Mid",
            "Armor_Gloves_DefenseValue_ArmorBoost_Normal",
            "Armor_Gloves_DefenseValue_ArmorBoost_Normal_Late",
            "Armor_Gloves_DefenseValue_ArmorBoost_Normal_Mid",
            "Armor_Gloves_DefenseValue_ArmorBoost_Small_Late",
            "Armor_Gloves_ReflectMelee",
            "Armor_Gloves_ReflectMelee_Large",
            "Armor_Heal_RegenerateStart_Garment",
            "Armor_Helmet_DefenseValue_Legendary_ArmorBoost",
            "Armor_Helmet_DefenseValue_Medium_ArmorBoost",
            "Armor_Helmet_Medium_ArmorDefense_Mod",
            "Armor_Helmet_Small_ArmorDefense_Mod",
            "Armor_Helmet_Target_Farsight",
            "Armor_Helmet_Target_TargetedPerception",
            "Armor_Large_AirResistance_Mod_Amulet",
            "Armor_Large_AirResistance_Mod_Amulet_Late",
            "Armor_Large_AirResistance_ModRing",
            "Armor_Large_AirResistance_ModRing_Late",
            "Armor_Large_ArmorDefense_Mod_LateMail",
            "Armor_Large_ArmorDefense_Mod_LatePlate",
            "Armor_Large_ArmorDefense_ModHelmet",
            "Armor_Large_EarthResistance_Mod_Amulet",
            "Armor_Large_EarthResistance_Mod_Amulet_Late",
            "Armor_Large_EarthResistance_ModRing",
            "Armor_Large_EarthResistance_ModRing_Late",
            "Armor_Large_FireResistance_Mod_Amulet",
            "Armor_Large_FireResistance_Mod_Amulet_Late",
            "Armor_Large_FireResistance_ModRing",
            "Armor_Large_FireResistance_ModRing_Late",
            "Armor_Large_WaterResistance_Mod_Amulet",
            "Armor_Large_WaterResistance_Mod_Amulet_Late",
            "Armor_Large_WaterResistance_ModRing",
            "Armor_Large_WaterResistance_ModRing_Late",
            "Armor_Legendary_ArmorDefense_ModMail",
            "Armor_Legendary_ArmorDefense_ModPlate",
            "Armor_Medium_ArmorDefense_ModMail",
            "Armor_Medium_ArmorDefense_ModMail_Late",
            "Armor_Medium_ArmorDefense_ModPlate",
            "Armor_Medium_ArmorDefense_ModPlate_Late",
            "Armor_Path_Firefly_Garment",
            "Armor_ReflectAll_Legendary",
            "Armor_ReflectMelee",
            "Armor_ReflectMelee_Large",
            "Armor_ReflectMelee_Large_Plate",
            "Armor_ReflectMelee_Plate",
            "Armor_Ring_Boost_BurnImmunity",
            "Armor_Ring_Boost_BurnImmunity_Late",
            "Armor_Ring_Boost_FreezeImmunity",
            "Armor_Ring_Boost_FreezeImmunity_Late",
            "Armor_Ring_Boost_PetrifiedImmunity",
            "Armor_Ring_Boost_PetrifiedImmunity_Late",
            "Armor_Ring_Boost_StunImmunity",
            "Armor_Ring_Boost_StunImmunity_Late",
            "Armor_Shield_Air_Amulet",
            "Armor_Shield_Earth_Amulet",
            "Armor_Shield_Fire_Amulet",
            "Armor_Shield_Water_Amulet",
            "Armor_Shoes_DefenseValue_ArmorBoost",
            "Armor_Shoes_DefenseValue_Large_ArmorBoost",
            "Armor_Shoes_DefenseValue_Legendary_ArmorBoost",
            "Armor_Shoes_DefenseValue_Medium_ArmorBoost",
            "Armor_Shoes_DefenseValue_Medium_ArmorBoost_Early",
            "Armor_Small_AirResistance_Mod",
            "Armor_Small_AirResistance_Mod_Amulet_Late",
            "Armor_Small_AirResistance_ModAmulet",
            "Armor_Small_AirResistance_ModAmulet_Large",
            "Armor_Small_AirResistance_ModRing",
            "Armor_Small_AirResistance_ModRing_Late",
            "Armor_Small_AirResistance_ModRingLarge",
            "Armor_Small_AllResist_Mod",
            "Armor_Small_ArmorDefense_ModLeather",
            "Armor_Small_ArmorDefense_ModMail",
            "Armor_Small_ArmorDefense_ModPlate",
            "Armor_Small_EarthResistance_Mod",
            "Armor_Small_EarthResistance_Mod_Amulet_Late",
            "Armor_Small_EarthResistance_ModAmulet",
            "Armor_Small_EarthResistance_ModAmulet_Large",
            "Armor_Small_EarthResistance_ModRing",
            "Armor_Small_EarthResistance_ModRing_Late",
            "Armor_Small_EarthResistance_ModRingLarge",
            "Armor_Small_FireResistance_Mod",
            "Armor_Small_FireResistance_Mod_Amulet_Late",
            "Armor_Small_FireResistance_ModAmulet",
            "Armor_Small_FireResistance_ModAmulet_Large",
            "Armor_Small_FireResistance_ModRing",
            "Armor_Small_FireResistance_ModRing_Late",
            "Armor_Small_FireResistance_ModRingLarge",
            "Armor_Small_Intelligence_Mod",
            "Armor_Small_Luck_Mod",
            "Armor_Small_Movement_Mod",
            "Armor_Small_Sneaking_Mod",
            "Armor_Small_Speed_Mod",
            "Armor_Small_Vitality_Mod",
            "Armor_Small_WaterResistance_Mod",
            "Armor_Small_WaterResistance_Mod_Amulet_Late",
            "Armor_Small_WaterResistance_ModAmulet",
            "Armor_Small_WaterResistance_ModAmulet_Large",
            "Armor_Small_WaterResistance_ModRing",
            "Armor_Small_WaterResistance_ModRing_Late",
            "Armor_Small_WaterResistance_ModRingLarge",
            "Armor_Summon_Undead_Garment",
            "Armor_Target_Immolate_Garment",
            "Armor_Target_InvisibilityTarget_Garment",
            "Armor_Target_PetrifyingTouch_Garment",
            "Armor_Target_PurifyingFire_Garment",
            "Armor_Teleportation_Resurrect_Garment",
            "Armor_Tornado_Air_Garment",
            "Armor_Unbreakable_Mod",
            "Armor_Unbreakable_Mod_Helmet",
            "Armor_Unbreakable_Mod_Plate",
            "Belt",
            "Shield_CrippledImmunity",
            "Shield_ElementalTortoise_Mod",
            "Shield_FreezeImmunity",
            "Shield_Giant_AirResistance_Mod",
            "Shield_Giant_EarthResistance_Mod",
            "Shield_Giant_FireResistance_Mod",
            "Shield_Giant_WaterResistance_Mod",
            "Shield_Large_AirResistance_Mod",
            "Shield_Large_Blocking_Mod",
            "Shield_Large_EarthResistance_Mod",
            "Shield_Large_FireResistance_Mod",
            "Shield_Large_WaterResistance_Mod",
            "Shield_LargeSingleHanded_Mod",
            "Shield_Legendary_AirResistance_Mod",
            "Shield_Legendary_EarthResistance_Mod",
            "Shield_Legendary_FireResistance_Mod",
            "Shield_Legendary_WaterResistance_Mod",
            "Shield_Medium_Blocking_Mod",
            "Shield_Medium_Blocking_Mod_Late",
            "Shield_Normal_AirResistance_Mod",
            "Shield_Normal_EarthResistance_Mod",
            "Shield_Normal_FireResistance_Mod",
            "Shield_Normal_Movement_Mod_Giant",
            "Shield_Normal_Movement_Mod_Large",
            "Shield_Normal_Movement_Mod_Medium",
            "Shield_Normal_WaterResistance_Mod",
            "Shield_PetrifiedImmunity",
            "Shield_Reflect_Melee_Air",
            "Shield_Reflect_Melee_Air_Large",
            "Shield_Reflect_Melee_Earth",
            "Shield_Reflect_Melee_Earth_Large",
            "Shield_Reflect_Melee_Fire",
            "Shield_Reflect_Melee_Fire_Large",
            "Shield_Reflect_Melee_Water",
            "Shield_Reflect_Melee_Water_Large",
            "Shield_ReflectMelee_Large",
            "Shield_ReflectMelee_Legendary",
            "Shield_ReflectMelee_Medium",
            "Shield_ReflectMelee_Small",
            "Shield_ReflectMelee_Small_Late",
            "Shield_Small_AirResistance_Mod",
            "Shield_Small_AirResistance_Mod_Late",
            "Shield_Small_Blocking_Mod",
            "Shield_Small_Blocking_Mod_Mid",
            "Shield_Small_Consitution_Mod",
            "Shield_Small_Durability_Mod",
            "Shield_Small_EarthResistance_Mod",
            "Shield_Small_EarthResistance_Mod_Late",
            "Shield_Small_FireResistance_Mod",
            "Shield_Small_FireResistance_Mod_Late",
            "Shield_Small_Luck_Mod",
            "Shield_Small_Movement_Mod",
            "Shield_Small_Movement_Mod_Large",
            "Shield_Small_Movement_Mod_Medium",
            "Shield_Small_ShadowResistance_Mod",
            "Shield_Small_WaterResistance_Mod",
            "Shield_Small_WaterResistance_Mod_Late",
            "Shield_Smallest_Blocking_Mod",
            "Shield_StunImmunity",
            "Shield_Unbreakable_Mod",
            "Shield_Value_Mod",
            "Weapon_Air_Legendary_Skill_WeaponBoost_Axe",
            "Weapon_Air_Legendary_Skill_WeaponBoost_Bow",
            "Weapon_Air_Legendary_Skill_WeaponBoost_Club",
            "Weapon_Air_Legendary_Skill_WeaponBoost_Crossbow",
            "Weapon_Air_Legendary_Skill_WeaponBoost_Knife",
            "Weapon_Air_Legendary_Skill_WeaponBoost_Spear",
            "Weapon_Air_Legendary_Skill_WeaponBoost_Sword",
            "Weapon_APCost_ModXBow",
            "Weapon_Blackrock_Boost_Combo",
            "Weapon_Bleeding_Large_WeaponBoost_All",
            "Weapon_Bleeding_Large_WeaponBoost_Axe",
            "Weapon_Bleeding_Large_WeaponBoost_Bow",
            "Weapon_Bleeding_Large_WeaponBoost_Knife",
            "Weapon_Bleeding_Large_WeaponBoost_Spear",
            "Weapon_Bleeding_Large_WeaponBoost_Sword",
            "Weapon_Bleeding_Large_WeaponBoost_Xbow",
            "Weapon_Bleeding_WeaponBoost_Axe",
            "Weapon_Bleeding_WeaponBoost_Bow",
            "Weapon_Bleeding_WeaponBoost_Knife",
            "Weapon_Bleeding_WeaponBoost_Spear",
            "Weapon_Bleeding_WeaponBoost_Sword",
            "Weapon_Bleeding_WeaponBoost_Xbow",
            "Weapon_Blind_Large_WeaponBoost_All",
            "Weapon_Blind_Large_WeaponBoost_Staff",
            "Weapon_Blind_Large_WeaponBoost_Wand",
            "Weapon_Blind_WeaponBoost_Staff",
            "Weapon_Blind_WeaponBoost_Wand",
            "Weapon_Cripple_Large_WeaponBoost_Axe_All",
            "Weapon_Cripple_Large_WeaponBoost_Axe_Late",
            "Weapon_Cripple_Large_WeaponBoost_Club_Late",
            "Weapon_Cripple_Large_WeaponBoost_Staff_Late",
            "Weapon_Cripple_Large_WeaponBoost_Sword_Late",
            "Weapon_Cripple_WeaponBoost_Axe",
            "Weapon_Cripple_WeaponBoost_Club",
            "Weapon_Cripple_WeaponBoost_Staff",
            "Weapon_Cripple_WeaponBoost_Sword",
            "Weapon_Crit_Giant_WeaponBoost",
            "Weapon_Crit_Giant_WeaponBoost_Late",
            "Weapon_Crit_Huge_WeaponBoost",
            "Weapon_Crit_Huge_WeaponBoost_Late",
            "Weapon_Crit_Inhuman_WeaponBoost",
            "Weapon_Cursed_Large_WeaponBoost_All",
            "Weapon_Cursed_Large_WeaponBoost_Staff",
            "Weapon_Cursed_Large_WeaponBoost_Wand",
            "Weapon_Cursed_WeaponBoost_Staff",
            "Weapon_Cursed_WeaponBoost_Wand",
            "Weapon_Damage_Mod_Axe",
            "Weapon_Damage_Mod_Club",
            "Weapon_Damage_Mod_ModKnife",
            "Weapon_Damage_Mod_Sword",
            "Weapon_Damage_Mod_Wand",
            "Weapon_Diseased_Large_WeaponBoost_Knife",
            "Weapon_Diseased_Large_WeaponBoost_Spear",
            "Weapon_Diseased_WeaponBoost_Knife",
            "Weapon_Diseased_WeaponBoost_Spear",
            "Weapon_Earth_Legendary_Skill_WeaponBoost_Axe",
            "Weapon_Earth_Legendary_Skill_WeaponBoost_Bow",
            "Weapon_Earth_Legendary_Skill_WeaponBoost_Club",
            "Weapon_Earth_Legendary_Skill_WeaponBoost_Crossbow",
            "Weapon_Earth_Legendary_Skill_WeaponBoost_Knife",
            "Weapon_Earth_Legendary_Skill_WeaponBoost_Spear",
            "Weapon_Earth_Legendary_Skill_WeaponBoost_Sword",
            "Weapon_Fear_Mod_Axe",
            "Weapon_Fear_Mod_Spear",
            "Weapon_Fear_Mod_Sword",
            "Weapon_FearLarge_Mod_All",
            "Weapon_FearLarge_Mod_Axe",
            "Weapon_FearLarge_Mod_Spear",
            "Weapon_FearLarge_Mod_Sword",
            "Weapon_Fire_Legendary_Skill_WeaponBoost_Axe",
            "Weapon_Fire_Legendary_Skill_WeaponBoost_Bow",
            "Weapon_Fire_Legendary_Skill_WeaponBoost_Club",
            "Weapon_Fire_Legendary_Skill_WeaponBoost_Crossbow",
            "Weapon_Fire_Legendary_Skill_WeaponBoost_Knife",
            "Weapon_Fire_Legendary_Skill_WeaponBoost_Spear",
            "Weapon_Fire_Legendary_Skill_WeaponBoost_Sword",
            "Weapon_Fortification_Mod_Axe",
            "Weapon_Fortification_Mod_Club",
            "Weapon_Fortification_Mod_Spear",
            "Weapon_Fortification_Mod_Sword",
            "Weapon_Giant_AirDamage_ModAxe",
            "Weapon_Giant_AirDamage_ModAxe_Late",
            "Weapon_Giant_AirDamage_ModBow",
            "Weapon_Giant_AirDamage_ModBow_Late",
            "Weapon_Giant_AirDamage_ModClub",
            "Weapon_Giant_AirDamage_ModClub_Late",
            "Weapon_Giant_AirDamage_ModKnife",
            "Weapon_Giant_AirDamage_ModKnife_Late",
            "Weapon_Giant_AirDamage_ModSpear_Late",
            "Weapon_Giant_AirDamage_ModSword",
            "Weapon_Giant_AirDamage_ModSword_Late",
            "Weapon_Giant_AirDamage_ModXBow",
            "Weapon_Giant_AirDamage_ModXBow_Late",
            "Weapon_Giant_EarthDamage_ModAxe",
            "Weapon_Giant_EarthDamage_ModAxe_Late",
            "Weapon_Giant_EarthDamage_ModBow",
            "Weapon_Giant_EarthDamage_ModBow_Late",
            "Weapon_Giant_EarthDamage_ModClub",
            "Weapon_Giant_EarthDamage_ModClub_Late",
            "Weapon_Giant_EarthDamage_ModKnife",
            "Weapon_Giant_EarthDamage_ModKnife_Late",
            "Weapon_Giant_EarthDamage_ModSpear_Late",
            "Weapon_Giant_EarthDamage_ModSword",
            "Weapon_Giant_EarthDamage_ModSword_Late",
            "Weapon_Giant_EarthDamage_ModXBow",
            "Weapon_Giant_EarthDamage_ModXBow_Late",
            "Weapon_Giant_FireDamage_ModAxe",
            "Weapon_Giant_FireDamage_ModAxe_Late",
            "Weapon_Giant_FireDamage_ModBow",
            "Weapon_Giant_FireDamage_ModBow_Late",
            "Weapon_Giant_FireDamage_ModClub",
            "Weapon_Giant_FireDamage_ModClub_Late",
            "Weapon_Giant_FireDamage_ModKnife",
            "Weapon_Giant_FireDamage_ModKnife_Late",
            "Weapon_Giant_FireDamage_ModSpear_Late",
            "Weapon_Giant_FireDamage_ModSword",
            "Weapon_Giant_FireDamage_ModSword_Late",
            "Weapon_Giant_FireDamage_ModXBow",
            "Weapon_Giant_FireDamage_ModXBow_Late",
            "Weapon_Giant_Vitality_Mod_Late",
            "Weapon_Giant_Vitality_Mod_Mid",
            "Weapon_Giant_WaterDamage_ModAxe",
            "Weapon_Giant_WaterDamage_ModAxe_Late",
            "Weapon_Giant_WaterDamage_ModBow",
            "Weapon_Giant_WaterDamage_ModBow_Late",
            "Weapon_Giant_WaterDamage_ModClub",
            "Weapon_Giant_WaterDamage_ModClub_Late",
            "Weapon_Giant_WaterDamage_ModKnife",
            "Weapon_Giant_WaterDamage_ModKnife_Late",
            "Weapon_Giant_WaterDamage_ModSpear_Late",
            "Weapon_Giant_WaterDamage_ModSword",
            "Weapon_Giant_WaterDamage_ModSword_Late",
            "Weapon_Giant_WaterDamage_ModXBow",
            "Weapon_Giant_WaterDamage_ModXBow_Late",
            "Weapon_Huge_Damage_Mod_2H",
            "Weapon_Huge_Damage_Mod_Axe",
            "Weapon_Huge_Damage_Mod_Club",
            "Weapon_Huge_Damage_Mod_Sword",
            "Weapon_Huge_Damage_Mod_Wand",
            "Weapon_Huge_Damage_ModKnife",
            "Weapon_Knockdown_Mod",
            "Weapon_Knockdown_Mod_Large",
            "Weapon_Large_AirDamage_ModAxe",
            "Weapon_Large_AirDamage_ModAxe_Late",
            "Weapon_Large_AirDamage_ModBow",
            "Weapon_Large_AirDamage_ModBow_Late",
            "Weapon_Large_AirDamage_ModClub",
            "Weapon_Large_AirDamage_ModClub_Late",
            "Weapon_Large_AirDamage_ModKnife",
            "Weapon_Large_AirDamage_ModKnife_Late",
            "Weapon_Large_AirDamage_ModSpear",
            "Weapon_Large_AirDamage_ModSpear_Late",
            "Weapon_Large_AirDamage_ModSword",
            "Weapon_Large_AirDamage_ModSword_Late",
            "Weapon_Large_AirDamage_ModXBow",
            "Weapon_Large_AirDamage_ModXBow_Late",
            "Weapon_Large_Crit_Mod_Early",
            "Weapon_Large_Crit_Mod_Late",
            "Weapon_Large_Damage_Mod",
            "Weapon_Large_Damage_Mod_2H",
            "Weapon_Large_Damage_Mod_Axe",
            "Weapon_Large_Damage_Mod_Club",
            "Weapon_Large_Damage_Mod_Sword",
            "Weapon_Large_Damage_Mod_Wand",
            "Weapon_Large_Damage_ModKnife",
            "Weapon_Large_EarthDamage_ModAxe",
            "Weapon_Large_EarthDamage_ModAxe_Late",
            "Weapon_Large_EarthDamage_ModBow",
            "Weapon_Large_EarthDamage_ModBow_Late",
            "Weapon_Large_EarthDamage_ModClub",
            "Weapon_Large_EarthDamage_ModClub_Late",
            "Weapon_Large_EarthDamage_ModKnife",
            "Weapon_Large_EarthDamage_ModKnife_Late",
            "Weapon_Large_EarthDamage_ModSpear",
            "Weapon_Large_EarthDamage_ModSpear_Late",
            "Weapon_Large_EarthDamage_ModSword",
            "Weapon_Large_EarthDamage_ModSword_Late",
            "Weapon_Large_EarthDamage_ModXBow",
            "Weapon_Large_EarthDamage_ModXBow_Late",
            "Weapon_Large_FireDamage_ModAxe",
            "Weapon_Large_FireDamage_ModAxe_Late",
            "Weapon_Large_FireDamage_ModBow",
            "Weapon_Large_FireDamage_ModBow_Late",
            "Weapon_Large_FireDamage_ModClub",
            "Weapon_Large_FireDamage_ModClub_Late",
            "Weapon_Large_FireDamage_ModKnife",
            "Weapon_Large_FireDamage_ModKnife_Late",
            "Weapon_Large_FireDamage_ModSpear",
            "Weapon_Large_FireDamage_ModSpear_Late",
            "Weapon_Large_FireDamage_ModSword",
            "Weapon_Large_FireDamage_ModSword_Late",
            "Weapon_Large_FireDamage_ModXBow",
            "Weapon_Large_FireDamage_ModXBow_Late",
            "Weapon_Large_Luck_Mod",
            "Weapon_Large_Vitality_Mod",
            "Weapon_Large_WaterDamage_ModAxe",
            "Weapon_Large_WaterDamage_ModAxe_Late",
            "Weapon_Large_WaterDamage_ModBow",
            "Weapon_Large_WaterDamage_ModBow_Late",
            "Weapon_Large_WaterDamage_ModClub",
            "Weapon_Large_WaterDamage_ModClub_Late",
            "Weapon_Large_WaterDamage_ModKnife",
            "Weapon_Large_WaterDamage_ModKnife_Late",
            "Weapon_Large_WaterDamage_ModSpear",
            "Weapon_Large_WaterDamage_ModSpear_Late",
            "Weapon_Large_WaterDamage_ModSword",
            "Weapon_Large_WaterDamage_ModSword_Late",
            "Weapon_Large_WaterDamage_ModXBow",
            "Weapon_Large_WaterDamage_ModXBow_Late",
            "Weapon_Leadership_Mod",
            "Weapon_Legendary_Vitality_Mod_Axe",
            "Weapon_Legendary_Vitality_Mod_Club",
            "Weapon_Legendary_Vitality_Mod_Spear",
            "Weapon_Legendary_Vitality_Mod_Sword",
            "Weapon_Medium_Damage_Mod",
            "Weapon_Medium_Damage_Mod_Axe",
            "Weapon_Medium_Damage_Mod_Club",
            "Weapon_Medium_Damage_Mod_Sword",
            "Weapon_Medium_Damage_Mod_Wand",
            "Weapon_Medium_Vitality_Mod",
            "Weapon_Movement_Dagger_WeaponBoost_Huge_Late",
            "Weapon_Movement_Dagger_WeaponBoost_Large_Late",
            "Weapon_Movement_Dagger_WeaponBoost_Late",
            "Weapon_Mute_Large_WeaponBoost_All",
            "Weapon_Mute_Large_WeaponBoost_Staff",
            "Weapon_Mute_Large_WeaponBoost_Wand",
            "Weapon_Mute_WeaponBoost_Staff",
            "Weapon_Mute_WeaponBoost_Wand",
            "Weapon_Normal_Damage_Mod_2H",
            "Weapon_Petrify_Large_WeaponBoost_All",
            "Weapon_Petrify_Large_WeaponBoost_Spear",
            "Weapon_Petrify_Large_WeaponBoost_Staff",
            "Weapon_Petrify_Large_WeaponBoost_Wand",
            "Weapon_Petrify_WeaponBoost_Spear",
            "Weapon_Petrify_WeaponBoost_Staff",
            "Weapon_Petrify_WeaponBoost_Wand",
            "Weapon_Raged_WeaponBoost_Axe",
            "Weapon_Raged_WeaponBoost_Bow",
            "Weapon_Raged_WeaponBoost_Club",
            "Weapon_Raged_WeaponBoost_Knife",
            "Weapon_Raged_WeaponBoost_Spear",
            "Weapon_Raged_WeaponBoost_Sword",
            "Weapon_Raged_WeaponBoost_XBow",
            "Weapon_Ranged_BowMod",
            "Weapon_Ranged_XBowMod",
            "Weapon_Scope_Perception_Boost",
            "Weapon_SingleHanded_WeaponBoost_ModAxe",
            "Weapon_SingleHanded_WeaponBoost_ModClub",
            "Weapon_SingleHanded_WeaponBoost_ModSword",
            "Weapon_Small_ActionPoint_Mod",
            "Weapon_Small_AirDamage_Mod",
            "Weapon_Small_AirDamage_ModAxe",
            "Weapon_Small_AirDamage_ModBow",
            "Weapon_Small_AirDamage_ModClub",
            "Weapon_Small_AirDamage_ModKnife",
            "Weapon_Small_AirDamage_ModKnife_Late",
            "Weapon_Small_AirDamage_ModSpear",
            "Weapon_Small_AirDamage_ModSword",
            "Weapon_Small_AirDamage_ModXBow",
            "Weapon_Small_Consitution_Mod",
            "Weapon_Small_Consitution_Mod_Late",
            "Weapon_Small_Crit_Mod",
            "Weapon_Small_Damage_Mod",
            "Weapon_Small_Damage_Mod_2H",
            "Weapon_Small_Damage_Mod_ModKnife",
            "Weapon_Small_Dexterity_ModBow",
            "Weapon_Small_Dexterity_ModBow_Late",
            "Weapon_Small_Dexterity_ModCrossbow",
            "Weapon_Small_Dexterity_ModCrossbow_Late",
            "Weapon_Small_Dexterity_ModKnife",
            "Weapon_Small_Dexterity_ModKnife_Late",
            "Weapon_Small_Dexterity_ModSpear",
            "Weapon_Small_Dexterity_ModSpear_Late",
            "Weapon_Small_Durability_Mod",
            "Weapon_Small_EarthDamage_Mod",
            "Weapon_Small_EarthDamage_ModAxe",
            "Weapon_Small_EarthDamage_ModBow",
            "Weapon_Small_EarthDamage_ModClub",
            "Weapon_Small_EarthDamage_ModKnife",
            "Weapon_Small_EarthDamage_ModKnife_Late",
            "Weapon_Small_EarthDamage_ModSpear",
            "Weapon_Small_EarthDamage_ModSword",
            "Weapon_Small_EarthDamage_ModXBow",
            "Weapon_Small_FireDamage_Mod",
            "Weapon_Small_FireDamage_ModAxe",
            "Weapon_Small_FireDamage_ModBow",
            "Weapon_Small_FireDamage_ModClub",
            "Weapon_Small_FireDamage_ModKnife",
            "Weapon_Small_FireDamage_ModKnife_Late",
            "Weapon_Small_FireDamage_ModSpear",
            "Weapon_Small_FireDamage_ModSword",
            "Weapon_Small_FireDamage_ModXBow",
            "Weapon_Small_Intelligence_ModStaff",
            "Weapon_Small_Intelligence_ModStaff_Late",
            "Weapon_Small_Intelligence_ModStaffLarge",
            "Weapon_Small_Intelligence_ModStaffLarge_Late",
            "Weapon_Small_Intelligence_ModWand",
            "Weapon_Small_Intelligence_ModWand_Late",
            "Weapon_Small_Perception_Mod",
            "Weapon_Small_Perception_Mod_Late",
            "Weapon_Small_PoisonDamage_Mod",
            "Weapon_Small_Speed_Mod",
            "Weapon_Small_Speed_Mod_Late",
            "Weapon_Small_Strength_ModAxe",
            "Weapon_Small_Strength_ModAxe_Late",
            "Weapon_Small_Strength_ModClub",
            "Weapon_Small_Strength_ModClub_Late",
            "Weapon_Small_Strength_ModSword",
            "Weapon_Small_Strength_ModSword_Late",
            "Weapon_Small_TormentedSoul_Mod",
            "Weapon_Small_Value_Mod",
            "Weapon_Small_Vitality_Mod",
            "Weapon_Small_WaterDamage_Mod",
            "Weapon_Small_WaterDamage_ModAxe",
            "Weapon_Small_WaterDamage_ModBow",
            "Weapon_Small_WaterDamage_ModClub",
            "Weapon_Small_WaterDamage_ModKnife",
            "Weapon_Small_WaterDamage_ModKnife_Late",
            "Weapon_Small_WaterDamage_ModSpear",
            "Weapon_Small_WaterDamage_ModSword",
            "Weapon_Small_WaterDamage_ModXBow",
            "Weapon_TwoHanded_WeaponBoost_ModAxe",
            "Weapon_TwoHanded_WeaponBoost_ModSword",
            "Weapon_Unbreakable_Mod",
            "Weapon_Water_Legendary_Skill_WeaponBoost_Axe",
            "Weapon_Water_Legendary_Skill_WeaponBoost_Bow",
            "Weapon_Water_Legendary_Skill_WeaponBoost_Club",
            "Weapon_Water_Legendary_Skill_WeaponBoost_Crossbow",
            "Weapon_Water_Legendary_Skill_WeaponBoost_Knife",
            "Weapon_Water_Legendary_Skill_WeaponBoost_Spear",
            "Weapon_Water_Legendary_Skill_WeaponBoost_Sword",
            "Weapon_WillPower_Mod"
        };

        public static string[] StatsBoosts =
        {
            "Has_Reflection\tFalse"
        };

        /// <summary>
        /// Generation boosts that is new to GenerationBoosts but exists in Online resource
        /// </summary>
        public static string[] GenerationBoostsAddOnline;

        public static string[] StatsBoostsAddedOnline;

        /// <summary>
        /// All generation boosts found in user's savegame
        /// </summary>
        public static string[] UserGenerationBoosts = { };

        public static string[] UserStatsBoosts = { };

        /// <summary>
        /// Generation boosts found in user's savegame but missing from bost GenerationBoosts and online resource
        /// </summary>
        public static string[] UnlistedGenerationBoosts = { };

        public static string[] UnlistedStatsBoosts = { };

        public static bool IsOnlineBoostsGenerated { get; private set; }

        public static async Task GetTableFromOnline()
        {
            const string urlAddress =
                @"https://raw.githubusercontent.com/tmxkn1/D-OS-Save-Editor/master/GenerationBoosts.txt";
            var request = WebRequest.Create(urlAddress);
            IsOnlineBoostsGenerated = false;

            using (var response = await request.GetResponseAsync())
            {
                using (var stream = response.GetResponseStream())
                {
                    if (stream == null) return;
                    var boosts = new List<string>();

                    using (var sr = new StreamReader(stream))
                    {
                        string line;
                        while ((line = await sr.ReadLineAsync()) != null)
                        {
                            if (GenerationBoosts.Contains(line.Trim())) continue;
                            boosts.Add(line.Trim());
                        }

                        GenerationBoostsAddOnline = boosts.ToArray();

                        IsOnlineBoostsGenerated = true;

                        GetUnlistedStrings();
                    }
                }
            }
        }

        public static async Task GetUnlistedStrings()
        {
            // if no save game has been loaded, return
            // this would be the case when GetTableFromOnline finishes before user loads any save game
            if (UserGenerationBoosts.Length < 1) return;

            // if no online boosts, submit nothing.
            // this would be the case if the online list is no longer available when development stops or user has no internet, or slow internet
            var tick = 0;
            while (!IsOnlineBoostsGenerated)
            {
                await Task.Delay(500);
                tick++;
                // time out at 120 seconds
                if (tick > 240)
                    return;
            }

            // get genBoost
            var genBoost = UserGenerationBoosts.Where(boost => !GenerationBoosts.Contains(boost))
                .Where(boost => !GenerationBoostsAddOnline.Contains(boost)).ToList();
            UnlistedGenerationBoosts = genBoost.ToArray();
        }

        public static Talent[] GetTalentArray()
        {
            var talents = new Talent[TalentNamesEffects.Length/2];

            for (var i = 0; i < TalentIsHidden.Length; i ++)
            {
                talents[i] = new Talent(i, TalentNamesEffects[i*2], TalentNamesEffects[i*2+1], TalentIsHidden[i]);
            }

            return talents;
        }
    }
}
